#!/bin/bash

# Script para configurar Cloudinary en producción (Render)
# filepath: c:\Users\flavi\OneDrive\Escritorio\LibroDeResolucionesV2\configurar-cloudinary-render.sh

echo "🌩️  CONFIGURACIÓN DE CLOUDINARY PARA RENDER"
echo "=========================================="
echo ""

echo "📋 PASOS PARA CONFIGURAR CLOUDINARY:"
echo ""

echo "1. 📝 CREAR CUENTA EN CLOUDINARY:"
echo "   - Ve a https://cloudinary.com/"
echo "   - Crea una cuenta gratuita"
echo "   - Anota los siguientes datos del Dashboard:"
echo "     * Cloud Name"
echo "     * API Key"
echo "     * API Secret"
echo ""

echo "2. ⚙️  CONFIGURAR VARIABLES EN RENDER:"
echo "   - Ve a tu Web Service en Render"
echo "   - Entra a 'Environment'"
echo "   - Agrega las siguientes variables:"
echo ""
echo "   Variable: CLOUDINARY_CLOUD_NAME"
echo "   Value: [tu_cloud_name_de_cloudinary]"
echo ""
echo "   Variable: CLOUDINARY_API_KEY"
echo "   Value: [tu_api_key_de_cloudinary]"
echo ""
echo "   Variable: CLOUDINARY_API_SECRET"
echo "   Value: [tu_api_secret_de_cloudinary]"
echo ""
echo "   Variable: NODE_ENV"
echo "   Value: production"
echo ""

echo "3. 🗃️  VARIABLES DE BASE DE DATOS POSTGRES (si no están configuradas):"
echo "   Variable: DATABASE_URL"
echo "   Value: [tu_postgres_url_de_render]"
echo ""
echo "   O individualmente:"
echo "   Variable: DB_HOST"
echo "   Value: [tu_postgres_host]"
echo ""
echo "   Variable: DB_PORT"
echo "   Value: 5432"
echo ""
echo "   Variable: DB_NAME"
echo "   Value: libro_resoluciones"
echo ""
echo "   Variable: DB_USER"
echo "   Value: libro_resoluciones_user"
echo ""
echo "   Variable: DB_PASSWORD"
echo "   Value: [tu_password_de_postgres]"
echo ""

echo "4. 🔑 OTRAS VARIABLES IMPORTANTES:"
echo "   Variable: JWT_SECRET_KEY"
echo "   Value: [una_clave_secreta_segura_de_64_caracteres]"
echo ""
echo "   Variable: FRONTEND_URL"
echo "   Value: https://libro-de-resoluciones-v2-9izd-fe0i5ihfg.vercel.app"
echo ""
echo "   Variable: PORT"
echo "   Value: 10000"
echo ""

echo "5. 🚀 DESPLEGAR:"
echo "   - Guarda las variables"
echo "   - Render redesplegará automáticamente"
echo "   - Las imágenes ahora se guardarán en Cloudinary"
echo "   - Los datos persistirán entre redespliegues"
echo ""

echo "6. ✅ VERIFICAR:"
echo "   - Crea una nueva resolución con imágenes"
echo "   - Verifica que las imágenes se muestren correctamente"
echo "   - Redespliega manualmente desde Render"
echo "   - Verifica que las imágenes sigan funcionando"
echo ""

echo "📖 BENEFICIOS DE CLOUDINARY:"
echo "   ✅ Almacenamiento persistente (no se pierde en redespliegues)"
echo "   ✅ Optimización automática de imágenes"
echo "   ✅ CDN global para carga rápida"
echo "   ✅ Transformaciones automáticas (resize, calidad)"
echo "   ✅ Soporte para múltiples formatos"
echo ""

echo "⚠️  IMPORTANTE:"
echo "   - En desarrollo local, seguirá usando almacenamiento local"
echo "   - En producción, usará Cloudinary automáticamente"
echo "   - La aplicación detecta el entorno automáticamente"
echo ""

echo "🔧 Si tienes problemas:"
echo "   1. Verifica que todas las variables estén configuradas"
echo "   2. Revisa los logs de Render para errores"
echo "   3. Confirma que la cuenta de Cloudinary esté activa"
echo ""
