#!/bin/bash

echo "🔧 CONFIGURACIÓN POSTGRESQL RENDER - SOLUCIÓN DEFINITIVA"
echo "======================================================="
echo ""
echo "📋 PROBLEMA ACTUAL:"
echo "  ❌ Error: getaddrinfo ENOTFOUND libro-resoluciones-db"
echo "  ❌ Backend no puede conectarse a PostgreSQL"
echo "  ❌ Error 500 en todas las operaciones de BD"
echo ""
echo "✅ SOLUCIÓN: CREAR POSTGRESQL EN RENDER"
echo "======================================"
echo ""

echo "🗄️ PASO 1: CREAR BASE DE DATOS"
echo "------------------------------"
echo "1. Ir a: https://dashboard.render.com"
echo "2. Hacer clic en: 'New +' → 'PostgreSQL'"
echo "3. Configurar:"
echo "   Name: libro-resoluciones-db"
echo "   Database: libro_resoluciones"
echo "   User: libro_user"
echo "   Region: Ohio (US East) - MISMA que tu backend"
echo "   Plan: Free"
echo "4. Hacer clic en: 'Create Database'"
echo "5. ESPERAR 2-3 minutos hasta que aparezca 'Available'"
echo ""

echo "🔗 PASO 2: OBTENER DATABASE_URL"
echo "------------------------------"
echo "1. En el dashboard de la BD recién creada"
echo "2. Ir a la sección 'Info'"
echo "3. Copiar 'Internal Database URL'"
echo ""
echo "   Formato esperado:"
echo "   postgresql://libro_user_xxxx:password@libro-resoluciones-db-xxxx.render.com:5432/libro_resoluciones"
echo ""

echo "⚙️ PASO 3: CONFIGURAR EN BACKEND"
echo "-------------------------------"
echo "1. Ir al servicio 'libroderesoluciones-api'"
echo "2. Environment → 'Add Environment Variable'"
echo "3. Agregar:"
echo ""
echo "   Key: DATABASE_URL"
echo "   Value: postgresql://libro_user_xxxx:password@libro-resoluciones-db-xxxx.render.com:5432/libro_resoluciones"
echo ""
echo "4. Hacer clic en 'Save Changes'"
echo ""

echo "🚀 PASO 4: REDESPLEGAR BACKEND"
echo "-----------------------------"
echo "1. Hacer clic en 'Manual Deploy'"
echo "2. Seleccionar 'Deploy latest commit'"
echo "3. Esperar 3-5 minutos"
echo ""

echo "🧪 PASO 5: VERIFICAR FUNCIONAMIENTO"
echo "==================================="
echo "curl https://libroderesoluciones-api.onrender.com/health"
echo "# Debe mostrar status: healthy sin errores"
echo ""
echo "curl https://libroderesoluciones-api.onrender.com/diagnose"
echo "# Debe mostrar database.status: connected"
echo ""
echo "curl -X POST https://libroderesoluciones-api.onrender.com/api/user/login \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"Nombre\":\"admin\",\"Contrasena\":\"admin123\"}'"
echo "# Debe retornar token JWT exitosamente"
echo ""

echo "⚠️ NOTAS IMPORTANTES:"
echo "====================="
echo "- Usar INTERNAL Database URL (no External)"
echo "- Backend y BD deben estar en la MISMA región"
echo "- Plan Free PostgreSQL tiene 1GB de límite"
echo "- La URL debe copiarse EXACTAMENTE como aparece"
echo ""

echo "🆘 SI HAY PROBLEMAS:"
echo "==================="
echo "1. Verificar que la BD esté 'Available' (no 'Creating')"
echo "2. Verificar que DATABASE_URL esté configurada correctamente"
echo "3. Verificar que backend y BD estén en misma región"
echo "4. Revisar logs del backend durante el startup"
echo ""

echo "⏰ TIEMPO TOTAL ESTIMADO: 10-15 minutos"
echo "💰 COSTO: $0 (PostgreSQL Free Plan)"
echo ""

echo "🎯 PRÓXIMO PASO INMEDIATO:"
echo "========================="
echo "👉 CREAR POSTGRESQL EN RENDER AHORA"
echo "📱 https://dashboard.render.com → New + → PostgreSQL"
