#!/bin/bash

echo "🔍 DIAGNÓSTICO RENDER POSTGRESQL - ERROR ENOTFOUND"
echo "================================================="
echo ""

echo "📊 ANÁLISIS DEL ERROR:"
echo "====================="
echo "❌ Error: getaddrinfo ENOTFOUND libro-resoluciones-db"
echo "❌ Ubicación: /opt/render/project/src/server/db/postgres-connection.js:26"
echo "❌ Causa: Hostname 'libro-resoluciones-db' no resuelve"
echo ""

echo "🔍 VARIABLES DE ENTORNO REQUERIDAS:"
echo "==================================="
echo "El código busca estas variables (con valores por defecto):"
echo ""
echo "DB_HOST=process.env.DB_HOST || 'localhost'"
echo "DB_USER=process.env.DB_USER || 'postgres'"
echo "DB_NAME=process.env.DB_NAME || 'libro_resoluciones'"
echo "DB_PASSWORD=process.env.DB_PASSWORD || 'admin123'"
echo "DB_PORT=process.env.DB_PORT || 5433"
echo ""

echo "🚨 PROBLEMA ACTUAL:"
echo "=================="
echo "En producción (Render), el código está usando:"
echo "- DB_HOST='localhost' (no existe en Render)"
echo "- O DB_HOST='libro-resoluciones-db' (no configurado)"
echo ""

echo "✅ SOLUCIÓN PASO A PASO:"
echo "======================="
echo ""

echo "PASO 1: CREAR POSTGRESQL DATABASE EN RENDER"
echo "-------------------------------------------"
echo "🌐 Dashboard: https://dashboard.render.com"
echo "1. New + → PostgreSQL"
echo "2. Name: libro-resoluciones-db"
echo "3. Database: libro_resoluciones"
echo "4. User: libro_user"
echo "5. Region: Same as backend"
echo "6. Plan: Free"
echo "7. Create Database"
echo ""

echo "PASO 2: OBTENER CREDENCIALES"
echo "----------------------------"
echo "Después de crear la BD, ir a su dashboard y copiar:"
echo ""
echo "📋 Internal Database URL (ejemplo):"
echo "   libro-resoluciones-db-xxxx.render.com"
echo ""
echo "📋 Credenciales completas:"
echo "   Username: libro_user_xxxx"
echo "   Password: abcd1234..."
echo "   Database: libro_resoluciones"
echo "   Port: 5432"
echo ""

echo "PASO 3: CONFIGURAR EN BACKEND"
echo "-----------------------------"
echo "Ir al servicio 'libroderesoluciones-api' → Environment:"
echo ""
echo "DB_HOST=libro-resoluciones-db-xxxx.render.com"
echo "DB_USER=libro_user_xxxx"
echo "DB_PASSWORD=abcd1234..."
echo "DB_NAME=libro_resoluciones"
echo "DB_PORT=5432"
echo ""

echo "PASO 4: REDEPLOY BACKEND"
echo "-----------------------"
echo "Manual Deploy → Deploy latest commit"
echo ""

echo "⚡ SOLUCIÓN ALTERNATIVA RÁPIDA:"
echo "=============================="
echo "Si necesitas una solución INMEDIATA:"
echo ""
echo "1. Usar SQLite temporalmente modificando connection.js"
echo "2. O usar una BD externa (como ElephantSQL/Supabase)"
echo "3. O usar el DATABASE_URL completo de Render"
echo ""

echo "🧪 COMANDO DE VERIFICACIÓN:"
echo "=========================="
echo "Después de configurar:"
echo ""
echo "curl https://libroderesoluciones-api.onrender.com/diagnose"
echo ""
echo "Debe mostrar:"
echo "- database.status: 'connected'"
echo "- database.error: null"
echo ""

echo "💡 TIPS IMPORTANTES:"
echo "==================="
echo "- Usar Internal Database URL (más rápido)"
echo "- Backend y BD en misma región (menor latencia)"
echo "- El plan Free tiene límites pero es suficiente para testing"
echo "- Guardar credenciales en lugar seguro"
echo ""

echo "⏰ TIEMPO TOTAL ESTIMADO: 10-15 minutos"
echo "💰 COSTO: $0 (PostgreSQL Free Plan)"
echo ""

echo "🆘 SI NECESITAS AYUDA:"
echo "====================="
echo "1. Verificar que la BD esté 'Available' (no 'Creating')"
echo "2. Copiar exactamente las credenciales del dashboard"
echo "3. Usar Internal URL, no External"
echo "4. Verificar logs del backend después del deploy"
echo ""

echo "🎯 PRÓXIMO PASO:"
echo "==============="
echo "👆 CREAR LA BASE DE DATOS POSTGRESQL EN RENDER AHORA"
echo "📱 https://dashboard.render.com → New + → PostgreSQL"
