#!/bin/bash

echo "🔍 DIAGNÓSTICO DE VARIABLES DE ENTORNO RENDER"
echo "============================================="

echo ""
echo "✅ VARIABLES CORRECTAS (MANTENER):"
echo "================================="
echo "CLOUDINARY_API_KEY ✅"
echo "CLOUDINARY_API_SECRET ✅" 
echo "CLOUDINARY_CLOUD_NAME ✅"
echo "CORS_ORIGIN_1 ✅"
echo "CORS_ORIGIN_2 ✅"
echo "FRONTEND_URL ✅"
echo "JWT_SECRET_KEY ✅"
echo "NODE_ENV ✅"
echo "PORT ✅"
echo ""

echo "⚠️ PROBLEMA IDENTIFICADO: MÚLTIPLES URLs DE BASE DE DATOS"
echo "========================================================"
echo ""
echo "Tienes 3 URLs diferentes de PostgreSQL:"
echo ""
echo "1. DATABASE_URL:"
echo "   postgresql://libro_resoluciones_1gp9_user:...@libro_resoluciones_1gp9"
echo ""
echo "2. DATABASE_URL_EXTERNAL:"  
echo "   postgresql://libro_resoluciones_1gp9_user:...@oregon-postgres.render.com/libro_resoluciones_1gp9"
echo ""
echo "3. POSTGRES_URL:"
echo "   postgresql://libro_resoluciones_user:...@libro_resoluciones"
echo ""

echo "🚨 PROBLEMA:"
echo "============"
echo "• Son 3 bases de datos DIFERENTES"
echo "• Tu código usa DATABASE_URL (la primera)"
echo "• Pero esa URL parece ser interna y no funciona"
echo "• DATABASE_URL_EXTERNAL es la que probablemente funcione"
echo ""

echo "🔧 SOLUCIÓN RECOMENDADA:"
echo "======================="
echo "1. USAR DATABASE_URL_EXTERNAL como DATABASE_URL"
echo "2. ELIMINAR variables redundantes"
echo ""

echo "🎯 CONFIGURACIÓN CORRECTA:"
echo "========================="
echo "MANTENER estas variables:"
echo ""
echo "# Base de datos (solo 1)"
echo "DATABASE_URL=postgresql://libro_resoluciones_1gp9_user:gi1xhsRlAmVGc6sFYjdKLZOrSRWadgp-dlrIIbgd3pr7SsIG1B.oregon-postgres.render.com/libro_resoluciones_1gp9"
echo ""
echo "# Cloudinary"
echo "CLOUDINARY_API_KEY=892008536741378"
echo "CLOUDINARY_API_SECRET=cRAxrYeOPFgkEAAQJNGSRdFn-bc"
echo "CLOUDINARY_CLOUD_NAME=dcbmui4db"
echo ""
echo "# CORS"
echo "CORS_ORIGIN_1=https://libro-de-resoluciones-v2-91zd.vercel.app/"
echo "CORS_ORIGIN_2=https://libroderesoluciones-api.onrender.com"
echo ""
echo "# JWT"
echo "JWT_SECRET_KEY=c4ad8b8b90024f7f00435096eca42ccf09642a35b0e309063104706534d9cf6d4dc9cdd69e00be87ce47cc9atced2d2ta3e8d016ae83c902Dcf2a14a"
echo ""
echo "# Sistema"
echo "NODE_ENV=production"
echo "PORT=10000"
echo "FRONTEND_URL=https://libro-de-resoluciones-v2-91zd.vercel.app/"
echo ""

echo "🗑️ ELIMINAR estas variables redundantes:"
echo "======================================="
echo "❌ DATABASE_URL_EXTERNAL (mover a DATABASE_URL)"
echo "❌ POSTGRES_URL (diferente base de datos)"
echo "❌ DB_HOST (redundante con DATABASE_URL)"
echo "❌ DB_NAME (redundante con DATABASE_URL)"
echo "❌ DB_PASSWORD (redundante con DATABASE_URL)"
echo "❌ DB_PORT (redundante con DATABASE_URL)"
echo "❌ DB_USER (redundante con DATABASE_URL)"
echo ""

echo "📋 PASOS PARA CORREGIR:"
echo "======================"
echo "1. En Render Environment Variables:"
echo "   • Cambiar DATABASE_URL por el valor de DATABASE_URL_EXTERNAL"
echo "   • Eliminar DATABASE_URL_EXTERNAL"
echo "   • Eliminar POSTGRES_URL"
echo "   • Eliminar DB_HOST, DB_NAME, DB_PASSWORD, DB_PORT, DB_USER"
echo ""
echo "2. Save Changes (redespliegue automático)"
echo ""
echo "3. Esperar 3-5 minutos"
echo ""
echo "4. Probar endpoints"
echo ""

echo "🧪 COMANDO DE PRUEBA:"
echo "===================="
echo "Después de corregir, ejecutar:"
echo ""
echo "curl -X POST 'https://libroderesoluciones-api.onrender.com/api/user/register' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"Nombre\":\"admin\",\"Contrasena\":\"admin123\",\"Rol\":\"admin\"}'"
echo ""
echo "✅ Debería responder: 'Usuario creado exitosamente'"
echo ""

echo "💡 DIAGNÓSTICO COMPLETADO"
echo "El problema es que tienes múltiples URLs de BD y estás usando la incorrecta"
