#!/bin/bash

echo "🔍 GUÍA COMPLETA: CONFIGURACIÓN CLOUDINARY PARA VERCEL"
echo "====================================================="

echo ""
echo "📍 1. ENCONTRAR CLOUD_NAME EN CLOUDINARY"
echo "========================================"
echo "🌐 Ve a: https://console.cloudinary.com"
echo "🔑 Inicia sesión en tu cuenta"
echo "📊 En el Dashboard principal, verás:"
echo ""
echo "   ┌─────────────────────────────────────┐"
echo "   │ Account Details                     │"
echo "   │ ─────────────────────────────────── │"
echo "   │ Cloud name: tu_cloud_name_aqui      │ ← ESTE ES EL VALOR"
echo "   │ API Key: 123456789                  │"
echo "   │ API Secret: [Hidden]                │"
echo "   └─────────────────────────────────────┘"
echo ""
echo "✅ Copia el 'Cloud name' exactamente como aparece"
echo "📝 Ejemplo: si aparece 'dxy123abc', usa 'dxy123abc'"
echo ""

echo "📍 2. CREAR/ENCONTRAR UPLOAD_PRESET"
echo "=================================="
echo "🔧 Opción A - Crear nuevo Upload Preset:"
echo "1. En Cloudinary Dashboard → Settings (⚙️)"
echo "2. Clic en 'Upload' tab"
echo "3. Scroll hasta 'Upload presets'"
echo "4. Clic en 'Add upload preset'"
echo "5. Configurar:"
echo "   - Preset name: libro-resoluciones-preset"
echo "   - Signing Mode: Unsigned"
echo "   - Folder: libro-resoluciones"
echo "   - Resource type: Auto"
echo "6. Save"
echo ""
echo "🔍 Opción B - Usar Upload Preset existente:"
echo "1. Settings → Upload tab"
echo "2. En 'Upload presets' verás una lista"
echo "3. Busca uno que sea 'Unsigned'"
echo "4. Copia el nombre exacto"
echo ""
echo "⚠️ IMPORTANTE: Debe ser 'Unsigned' para funcionar desde el frontend"
echo ""

echo "📍 3. VERIFICAR CONFIGURACIÓN ACTUAL"
echo "=================================="
echo "🔍 Revisando archivos de configuración actuales..."

# Buscar referencias a Cloudinary en el código
if [ -f "server/config/cloudinary.js" ]; then
    echo "📄 Encontrado: server/config/cloudinary.js"
    echo "   Cloud name actual:"
    grep -n "cloud_name" server/config/cloudinary.js | head -1
    echo ""
fi

if [ -f "front/.env" ]; then
    echo "📄 Encontrado: front/.env"
    echo "   Variables actuales:"
    grep "CLOUDINARY\|VITE_CLOUDINARY" front/.env
    echo ""
elif [ -f ".env" ]; then
    echo "📄 Encontrado: .env (raíz)"
    echo "   Variables actuales:"
    grep "CLOUDINARY\|VITE_CLOUDINARY" .env
    echo ""
else
    echo "📄 No se encontró archivo .env"
fi

echo "📍 4. CONFIGURAR EN VERCEL"
echo "========================="
echo "🌐 Ve a: https://vercel.com/dashboard"
echo "🎯 Selecciona tu proyecto frontend"
echo "⚙️ Settings → Environment Variables"
echo "➕ Add New Variable:"
echo ""
echo "Variable 1:"
echo "   Name: VITE_CLOUDINARY_CLOUD_NAME"
echo "   Value: [tu cloud_name de paso 1]"
echo "   Environment: Production, Preview, Development"
echo ""
echo "Variable 2:"
echo "   Name: VITE_CLOUDINARY_UPLOAD_PRESET"
echo "   Value: [tu upload_preset de paso 2]"
echo "   Environment: Production, Preview, Development"
echo ""

echo "📍 5. CONFIGURACIÓN VITE_BUILD_OUTPUT"
echo "====================================="
echo "ℹ️ VITE_BUILD_OUTPUT no es necesario configurar porque:"
echo "   - Vite usa 'dist' por defecto"
echo "   - Vercel detecta automáticamente el build folder"
echo "   - Solo se necesita si cambias la configuración de build"
echo ""
echo "✅ Para la mayoría de casos: NO necesitas VITE_BUILD_OUTPUT"
echo ""

echo "📍 6. EJEMPLO DE CONFIGURACIÓN COMPLETA"
echo "======================================"
echo "En Vercel Environment Variables:"
echo ""
echo "VITE_API_URL=https://libroderesoluciones-api.onrender.com"
echo "VITE_CLOUDINARY_CLOUD_NAME=dxy123abc"
echo "VITE_CLOUDINARY_UPLOAD_PRESET=libro-resoluciones-preset"
echo "NODE_ENV=production"
echo ""

echo "🧪 VERIFICACIÓN"
echo "==============="
echo "Después de configurar, verifica que funciona:"
echo ""
echo "1. Redesplegar en Vercel"
echo "2. Abrir consola del navegador"
echo "3. Buscar logs como:"
echo "   'Cloudinary configurado con cloud_name: dxy123abc'"
echo "4. Probar subir una imagen"
echo ""

echo "🆘 SOLUCIÓN DE PROBLEMAS"
echo "======================="
echo "❌ Si aparece 'Upload preset not found':"
echo "   → Verificar que el preset sea 'Unsigned'"
echo "   → Usar el nombre exacto del preset"
echo ""
echo "❌ Si aparece 'Invalid cloud_name':"
echo "   → Copiar exactamente como aparece en Cloudinary"
echo "   → No incluir espacios al inicio/final"
echo ""
echo "❌ Si las variables no se cargan:"
echo "   → Verificar que empiecen con 'VITE_'"
echo "   → Redesplegar después de agregar variables"
echo ""

echo "✅ Configuración completada siguiendo esta guía"
