#!/bin/bash

echo "⚡ SOLUCIÓN ALTERNATIVA RÁPIDA - SUPABASE POSTGRESQL"
echo "==================================================="
echo ""
echo "Si quieres una solución INMEDIATA mientras configuras Render:"
echo ""

echo "🚀 OPCIÓN A: SUPABASE (5 MINUTOS)"
echo "================================"
echo "1. Ir a: https://supabase.com"
echo "2. Crear cuenta gratuita"
echo "3. Crear nuevo proyecto:"
echo "   - Project name: libro-resoluciones"
echo "   - Database Password: admin123"
echo "   - Region: US East (más cercano)"
echo "4. Esperar 2 minutos hasta que se cree"
echo "5. Ir a Settings → Database"
echo "6. Copiar 'Connection string' bajo 'Connection pooling'"
echo ""
echo "Formato esperado:"
echo "postgresql://postgres.xxxx:admin123@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
echo ""

echo "🚀 OPCIÓN B: NEON.TECH (3 MINUTOS)"
echo "================================="
echo "1. Ir a: https://neon.tech"
echo "2. Crear cuenta con GitHub"
echo "3. Crear proyecto:"
echo "   - Project name: libro-resoluciones"
echo "   - Database: libro_resoluciones"
echo "   - Region: US East"
echo "4. Copiar Connection String"
echo ""

echo "⚙️ CONFIGURACIÓN EN RENDER (AMBAS OPCIONES)"
echo "==========================================="
echo "1. Ir a libroderesoluciones-api → Environment"
echo "2. Agregar variable:"
echo "   Key: DATABASE_URL"
echo "   Value: [la URL copiada del servicio elegido]"
echo "3. Manual Deploy"
echo ""

echo "✅ VENTAJAS DE LAS ALTERNATIVAS:"
echo "==============================="
echo "- ⚡ Configuración en 3-5 minutos"
echo "- 🆓 Completamente gratis"
echo "- 🚀 Mejor rendimiento que Render Free"
echo "- 🔧 Fácil migración posterior a Render si lo deseas"
echo ""

echo "🧪 VERIFICACIÓN INMEDIATA:"
echo "=========================="
echo "Una vez configurada cualquier opción:"
echo ""
echo "curl https://libroderesoluciones-api.onrender.com/health"
echo "# Debería funcionar inmediatamente"
echo ""

echo "🎯 RECOMENDACIÓN:"
echo "================="
echo "Usa SUPABASE para una solución rápida ahora,"
echo "y opcionalmente migra a Render PostgreSQL después."
