#!/bin/bash

echo "🔍 VERIFICACIÓN MANUAL DE CLOUDINARY"
echo "===================================="
echo ""

echo "📊 Método 1: Verificar en Dashboard de Render"
echo "============================================="
echo "1. Ve a: https://dashboard.render.com"
echo "2. Selecciona: libroderesoluciones-api"
echo "3. Ve a: Environment"
echo "4. Busca estas variables:"
echo "   - CLOUDINARY_CLOUD_NAME"
echo "   - CLOUDINARY_API_KEY"
echo "   - CLOUDINARY_API_SECRET"
echo ""
echo "✅ Si las 3 variables están configuradas → Cloudinary ACTIVO"
echo "❌ Si falta alguna variable → Usando almacenamiento local"
echo ""

echo "📂 Método 2: Verificar en Cloudinary Dashboard"
echo "=============================================="
echo "1. Ve a: https://cloudinary.com/console"
echo "2. Ve a: Media Library"
echo "3. Busca carpeta: libro-resoluciones"
echo "4. Si hay imágenes → El sistema está subiendo a Cloudinary"
echo ""

echo "🔍 Método 3: Verificar comportamiento del upload"
echo "==============================================="
echo "En tu aplicación web:"
echo "1. Ve a la sección de cargar resoluciones"
echo "2. Sube una imagen"
echo "3. Inspecciona la URL de la imagen:"
echo ""
echo "✅ Si la URL es algo como:"
echo "   https://res.cloudinary.com/tu-cloud-name/image/upload/..."
echo "   → Cloudinary FUNCIONANDO"
echo ""
echo "❌ Si la URL es algo como:"
echo "   https://libroderesoluciones-api.onrender.com/uploads/..."
echo "   → Usando almacenamiento local"
echo ""

echo "📋 Método 4: Verificar logs del servidor"
echo "========================================"
echo "En el dashboard de Render:"
echo "1. Ve a: Logs"
echo "2. Busca al inicio del log:"
echo ""
echo "✅ Si ves: '📁 Usando Cloudinary para uploads'"
echo "   → Cloudinary configurado"
echo ""
echo "❌ Si ves: '📁 Usando almacenamiento local para uploads'"
echo "   → Cloudinary NO configurado"
echo ""

echo "🔧 CONFIGURAR CLOUDINARY EN RENDER"
echo "=================================="
echo ""
echo "Si Cloudinary NO está configurado:"
echo ""
echo "1. Ve a: https://cloudinary.com/console"
echo "2. Copia estas credenciales:"
echo "   - Cloud Name"
echo "   - API Key"
echo "   - API Secret"
echo ""
echo "3. Ve a: https://dashboard.render.com"
echo "4. Selecciona: libroderesoluciones-api"
echo "5. Ve a: Environment"
echo "6. Agrega estas variables:"
echo ""
echo "   CLOUDINARY_CLOUD_NAME=tu-cloud-name"
echo "   CLOUDINARY_API_KEY=tu-api-key"
echo "   CLOUDINARY_API_SECRET=tu-api-secret"
echo ""
echo "7. Guarda cambios"
echo "8. El servidor se redesplegará automáticamente"
echo ""

echo "⏰ VERIFICACIÓN AUTOMÁTICA EN 2 MINUTOS"
echo "======================================="
echo ""
echo "Una vez que Render termine el deploy, ejecuta:"
echo "curl https://libroderesoluciones-api.onrender.com/api/cloudinary/status"
echo ""
echo "O ejecuta el script completo:"
echo "bash verificar-cloudinary.sh"
